name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Github checkout
        uses: actions/checkout@v2

      - name: Install and build
        run: pnpm i --frozen-lockfile && pnpm build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEALPLANNER_DDB4F }}'
          channelId: live
          projectId: mealplanner-ddb4f
